
const DEVELOPMENT = {
    FRONT_END_URL: process.env.DEVELOPMENT_FRONT_END_URL
};
const PRODUCTION = {
    FRONT_END_URL: process.env.PRODUCTION_FRONT_END_URL
};

module.exports = { DEVELOPMENT, PRODUCTION }